m<-matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3) 
print(m)
arr <- array(1:18, dim = c(3,3,2))
print(arr)
colors <- c("Red", "Blue", "Green", "Red", "Blue")
f <- factor(colors)
print(f)
Name <- c("Aman","Riya","Rohan") 
Language <- c("R","Python","Java") 
Age <- c(21,22,23)
df <- data.frame(Name, Language, Age)
print(df)
Gender <- c("Male","Female","Male")
Height <- c(170,160,175) 
Weight <- c(70,55,75) 
Age <- c(25,22,30)
family_info <- data.frame(Gender, Height, Weight, Age) 
print(family_info)